---

- name:  Windows Update
  hosts: all
  strategy: free
  ignore_errors: yes
  gather_facts: false
  tasks:
    - name: Run Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        register: result
        reboot: no
...
